name: SSH Key Generation and Usage

on:
  workflow_dispatch: 

jobs:
  ssh-keygen:
    runs-on: ubuntu-latest

    steps:
    - name: Generate SSH key
      id: ssh_key
      run: |
        ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -f ~/.ssh/id_rsa -N ""
        echo "KEY=$(cat ~/.ssh/id_rsa.pub)" >> $GITHUB_OUTPUT

    - name: use key in next steps
      run: ${{ steps.ssh_key.outputs.KEY }}
